In [6]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
voc_size=500

In [11]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[185, 436, 269, 32], [185, 436, 269, 220], [185, 474, 269, 229], [436, 221, 145, 264, 393], [436, 221, 145, 264, 399], [131, 185, 177, 269, 124], [17, 478, 7, 264]]


In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 185 436 269  32]
 [  0   0   0   0 185 436 269 220]
 [  0   0   0   0 185 474 269 229]
 [  0   0   0 436 221 145 264 393]
 [  0   0   0 436 221 145 264 399]
 [  0   0   0 131 185 177 269 124]
 [  0   0   0   0  17 478   7 264]]


In [15]:
print(embedded_docs.shape)  # Check the shape of your input


(7, 8)


In [16]:
dim=10

In [22]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (8, 10)                │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
embedded_docs[0]

array([  0,   0,   0,   0, 185, 436, 269,  32])

In [31]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[-0.01970457, -0.01699859,  0.04439935, -0.03036184, -0.03459074,
        -0.01209968, -0.02287563,  0.00539842, -0.04450157,  0.01268416],
       [-0.01970457, -0.01699859,  0.04439935, -0.03036184, -0.03459074,
        -0.01209968, -0.02287563,  0.00539842, -0.04450157,  0.01268416],
       [-0.01970457, -0.01699859,  0.04439935, -0.03036184, -0.03459074,
        -0.01209968, -0.02287563,  0.00539842, -0.04450157,  0.01268416],
       [-0.01970457, -0.01699859,  0.04439935, -0.03036184, -0.03459074,
        -0.01209968, -0.02287563,  0.00539842, -0.04450157,  0.01268416],
       [-0.03317159,  0.00239196, -0.0225852 , -0.01251155, -0.03931029,
         0.04927698,  0.01695526,  0.00218304,  0.01468945, -0.0201211 ],
       [ 0.01504112, -0.0403113 ,  0.03408039, -0.00369634, -0.0079179 ,
         0.04086589,  0.00277994, -0.04204601,  0.01379211,  0.00234915],
       [ 0.01184673,  0.0140701 ,  0.00061559, -0.03250324,  0.02156701,
         0.02112864, -0.01099672,  0.02320522

In [ ]:
print(model.predict(embedded_docs))

In [33]:
embedded_docs[0]

array([  0,   0,   0,   0, 185, 436, 269,  32])

In [ ]:
print(model.predict(embedded_docs)[0])